### ISSUE TITLE
Editor doesn't support attribute update

### ISSUE THREAD

**Issue by arkihillel** [Juicy/juicy-ace-editor#11]
At least it seems like so. I've been fiddling around with Polymer 1.2:

This works:
```
<juicy-ace-editor 
    mode="ace/mode/sqlserver">
</juicy-ace-editor>
```

This doesn't:
```
<juicy-ace-editor 
    mode="[[syntax]]">
</juicy-ace-editor>

…

syntax: {
    type: String,
    value: 'ace/mode/sqlserver'
}
```

**Comment by tomalec** [comment]
Have you tried  `$=`?
```html
<juicy-ace-editor 
    mode$="[[syntax]]">
```

This is not a Polymer Element, therefore it does not follow Polymer specific protocol of setting attribute via property.

So, you need to use Polymer binding syntax applicable for native & non-polymer elements.

**Comment by tomalec** [comment]
@arkihillel I hope the above solved your problem, if not, feel free to re-open.
