### ISSUE TITLE
The editor doesn't work in FF

### ISSUE THREAD

**Issue by vashchenkov** [Juicy/juicy-ace-editor#12]
I try to use ACE editor in complex card.
I have an error
TypeError: this.createShadowRoot is not a function
How can I fix this?

**Comment by xabufr** [comment]
According to <https://github.com/webcomponents/webcomponentsjs#releases>, you should try to include `webcomponents.js`, as the lite version doesn't include polyfill for shadow dom.

**Comment by tomalec** [comment]
@vashchenkov did it help?

**Comment by tomalec** [comment]
@vashchenkov  I hope the above solved your problem, if not, feel free to re-open.
