### ISSUE TITLE
Set #juicy-ace-editor-container position to relative

### ISSUE THREAD

**Issue by antoinegoutagny** [Juicy/juicy-ace-editor#17]
With the current settings, _#juicy-ace-editor-container_'s position is absolute. That means the _juicy-ace-editor_ component will never take on the full height of the editor, and following sibling elements end up over the editor box.

Changing juicy-ace-editor-container's position to relative fixes the issue and does not seem to have any-side effect (as far as I can tell). Is it possible to either change that setting, or at least provide a css variable so an implementer can have control over that ?

**Comment by tomalec** [comment]
Thanks for feedback @antoinegoutagny. Fair point. It seems to be some legacy workaround for something I cannot remember, or just a bug.

I'll test few things around, and fix it.

**Comment by tomalec** [comment]
I have change it to use `display:flex` instead of `position: absolute`.
It's released as [1.2.0](https://github.com/Juicy/juicy-ace-editor/releases/tag/1.2.0).

@antoinegoutagny I hope it works for you as well, if not please let me know.
