### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by Mackiovello** [Juicy/juicy-ace-editor#29]
From 

> Custom Element with Ace(http://ace.c9.io/) code editor

To

> Custom Element with the [Ace](http://ace.c9.io/) code editor

Relevant to Starcounter/TechComm#337

**Comment by alshakero** [comment]
In description? GH doesn't support MD there.

**Comment by Mackiovello** [comment]
Oh, okay. Let's delete the link then, it's still in the README. Just change to "...with **the* Ace..."

**Comment by alshakero** [comment]
Done.
