### ISSUE TITLE
Dynamic Height

### ISSUE THREAD

**Issue by bmodeprogrammer** [Juicy/juicy-ace-editor#33]
Is it possible to has the editor with Dynamic Height?
If is, can you give an example how to do it.

Thanks

**Comment by warpech** [comment]
This custom element is just a wrapper for Ace Editor, so it will not offer more featuers than Ace has.

AFAIK, in Ace Editor you can achieve this functionality with custom config and some scripting: https://ace.c9.io/demo/autoresize.html

`juicy-ace-editor` exposes Ace Editor instance as `editor` property (see https://github.com/Juicy/juicy-ace-editor).

Have you tried to hook this up together?

**Comment by tomalec** [comment]
Fixed in https://github.com/Juicy/juicy-ace-editor/pull/43
