### ISSUE TITLE
Switch to npm

### ISSUE THREAD

**Issue by lastmjs** [Juicy/juicy-ace-editor#34]
Are you planning on making this element available on npm soon?

**Comment by warpech** [comment]
I just did that for you: https://www.npmjs.com/package/juicy-ace-editor

Can you pls verify if this works for you?

We have more custom elements and would like to support both Bower and NPM. Any suggestions how to approach this in a productive way?

**Comment by lastmjs** [comment]
Sweet, I will check this out very soon. Productive way...personally, I plan on moving all of my custom elements to npm and not supporting bower. I might leave up previous versions of my elements on bower, but moving forward bower will not be supported, considering it is deprecated. Current users will still be able to use all of the functionality they have integrated into their systems with the elements installed from bower, but if they want the latest they'll have to deal with the fact that npm is now the way to go. That's how I'm approaching it.

If you really want to support both package managers...I really don't know. You might look to Polymer for how they're planning on doing things. I believe they've put a lot of thought into bower/npm.

I'll let you know how npm goes very soon.

**Comment by lastmjs** [comment]
It almost works, but I don't think the ace builds were included as dependencies in the package.json. I'm getting a 404 when requesting these files:

```
<script src="../ace-builds/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="../ace-builds/src-min-noconflict/ext-searchbox.js" type="text/javascript" charset="utf-8"></script>
```

**Comment by warpech** [comment]
Supporting Bower is usually a no-brainer, all you need to do is to tag a commit with the version number. I think we will keep Bower compatibility for a long while because it happens automatically.

> It almost works, but I don't think the ace builds were included as dependencies in the package.json. I'm getting a 404 when requesting these files:

What would be a typical way to do this with HTML Imports in npm? If I just add [`ace-builds`](https://www.npmjs.com/package/ace-builds) as a `dependency` in package.json, it will end up in `node_modules`. Is that ok?

**Comment by lastmjs** [comment]
That should work

**Comment by warpech** [comment]
Thanks, could you pls check the release https://github.com/Juicy/juicy-ace-editor/releases/tag/2.0.5?

Pls reopen if you still experience some problems with installing through NPM.
