### ISSUE TITLE
Polymer 3.0 support?

### ISSUE THREAD

**Issue by kkimdev** [Juicy/juicy-ace-editor#37]
https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview

**Comment by lastmjs** [comment]
Polymer 3 support should only require moving to ES Modules as far as I understand it. What can we do to get the move to ES Modules moving?

**Comment by kkimdev** [comment]
I think we should try auto converter https://github.com/Polymer/polymer-modulizer

It looks like paper elements maintain 2.0 source code and auto-generate 3.0. See https://github.com/PolymerElements/paper-button/ branch named 3.0 __auto_generated_3.0_preview .

Though, I think it's good to wait official 3.0 launch (supposed to be very soon, my guess is upcoming Google IO in May) and follow their official guideline for maintaining elements for all 1.0, 2.0, and 3.0.

**Comment by lastmjs** [comment]
This project doesn't use Polymer, except as a Bower dev dependency. The element itself is a vanilla HTMLElement.

**Comment by lastmjs** [comment]
This issue and [this issue](https://github.com/Juicy/juicy-ace-editor/issues/39) are accomplishing the same thing

**Comment by kkimdev** [comment]
Closing in favor of #39
