### ISSUE TITLE
Release the gh-pages branch as tag 0.0.3

### ISSUE THREAD

**Issue by thongdong7** [Juicy/juicy-ace-editor#6]
I have an issue when use juicy-ace-editor tag inside my custom Polymer element. The CSS of ace editor is not applied, so the content is broken.

I tried to install use the latest commit and it works:
`bower install juicy-ace-editor#38814bef170265156fd94043c4a45a67615392b9 --save`

Could you please release the latest commit as tag 0.0.4?

**Comment by tomalec** [comment]
Thanks for reporting @thongdong7 :)
[0.0.4](https://github.com/Juicy/juicy-ace-editor/releases/tag/0.0.4) released
