### ISSUE TITLE
Ace.c9.io editor configuration

### ISSUE THREAD

**Issue by debayan31** [Juicy/juicy-ace-editor#7]
Hi,

I am very new in ace.c9.io editor.

From ace official site I got kitchen-sink demo code which is pretty good.

But I am not understanding how can I able to get editor content(in screen shot rectangular highlighted area).

My requirement is something like,
whenever I click to save button (highlighted area) editor content get saved in some different file. For that reason I need  editor content.

Referring screen shot for understanding. 

I need some guidance regarding this.

Thanks In advance.

Also demo code of ace editior.

  <div id="editor-container"></div>
  <script src="src/ace.js" data-ace-base="src" type="text/javascript" charset="utf-8"></script>
  <script src="src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
  <script src="src/keybinding-vim.js"></script>
  <script src="src/keybinding-emacs.js"></script>
  <script src="demo/kitchen-sink/demo.js"></script>
  <script type="text/javascript" charset="utf-8">
    require("kitchen-sink/demo");
  </script>

![acescreenshot](https://cloud.githubusercontent.com/assets/11749797/7652596/c40238e4-fb2b-11e4-9482-dba4c6fa98de.jpg)

Debayan

**Comment by tomalec** [comment]
As `<juicy-ace-editor>` exposes entire ACE API, you can get the content by
```javascript
var juicyAce = document.querySelector("juicy-ace-editor");
var myContent = juicyAce.editor.getValue()
```

(Check on Juicy kitchen-sink ;) http://juicy.github.io/juicy-ace-editor/kitchen-sink.html )

**Comment by debayan31** [comment]
Thanks a ton.

**Comment by tomalec** [comment]
You are welcome :) could we close this issue?

**Comment by debayan31** [comment]
Whatever I am writing in this editor,Is it possible to add those new written code in "DemoJavascript.js" file.

**Comment by tomalec** [comment]
I'm not sure if I get you right, do you ask if is it possible to use text content of editor, and save it as file?
I believe in general it is ;) 

How to do that, depends on your case, and detailed requirement. Whether you want to save it from browser to server, and store there, serve from browser to be "downloaded" to local, or use some direct magic with node-webkit. For example you may use http://blog.teamtreehouse.com/building-an-html5-text-editor-with-the-filesystem-apis

I believe saving a file is feature separated far from `<juicy-ace-editor>` element, as it just (edits and) serves the text, which you can used in your application as you want.

**Comment by debayan31** [comment]
Ok thanks a lot tom.
