### ISSUE TITLE
Polymer 1.0?

### ISSUE THREAD

**Issue by jencarlile** [Juicy/juicy-ace-editor#8]
is there a plan to port this element to Polymer 1.0?  Thanks!

**Comment by tomalec** [comment]
There is :) but no dates yet, hopefully we will be able to make  that within this month, as we already progressing, with other elements.

**Comment by tomalec** [comment]
@jencarlile, it occurred easier than I thought, as I forgot it's a VanillaJS component ;) 
I have just released [1.0.0](https://github.com/Juicy/juicy-ace-editor/releases/tag/1.0.0) which works with latest webcomponents polyfill (=> Polymer). You can also check how kitchen sink works with Polymer 1.0.9 in [separate branch](https://github.com/Juicy/juicy-ace-editor/tree/polymer_1.0) - I will merge this demo to gh-pages, once entire juicy.github.io will be migrated to Polymer 1.0.

Thanks for you feedback! :)
